# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 02:07
from __future__ import unicode_literals

import app1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
                ('likes', models.IntegerField(default=0)),
                ('images', models.ImageField(blank=True, null=True, upload_to=app1.models.desti)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Division')),
            ],
        ),
    ]
