# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 16:05
from __future__ import unicode_literals

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to=app1.models.user_desti),
        ),
        migrations.AlterField(
            model_name='place',
            name='des',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
