# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='des',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
