# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread', models.BooleanField(default=True)),
                ('notify_from', models.TextField(max_length=50)),
                ('ref_type', models.TextField(max_length=50)),
                ('ref_value', models.TextField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='des',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
