# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_picture_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
