# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20170725_1739'),
        ('app1', '0003_auto_20170726_0230'),
    ]

    operations = [
    ]
