# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-17 04:06
from __future__ import unicode_literals

import app1.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='des',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='page',
            name='images',
            field=models.ImageField(default='', upload_to=app1.models.desti),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='page',
            name='likes',
        ),
        migrations.AddField(
            model_name='page',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
