# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-05 11:09
from __future__ import unicode_literals

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20170130_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.ImageField(upload_to=app1.models.desti),
        ),
    ]
