# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-22 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20170121_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='pic',
        ),
        migrations.AlterField(
            model_name='image',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app1.Page'),
        ),
    ]
