# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20170205_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
