# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app1', '0006_auto_20170319_0158'),
        ('app1', '0006_auto_20170318_2033'),
    ]

    operations = [
    ]
