# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20170728_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
