# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 23:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0007_merge_20170319_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='meta_key',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meta_value',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
