# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20170729_0254'),
        ('app1', '0008_auto_20170730_1308'),
    ]

    operations = [
    ]
