# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_merge_20170730_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='budget',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='member',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='type_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Type'),
        ),
    ]
