# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-31 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_merge_20170730_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField()),
                ('story_id', models.IntegerField()),
            ],
        ),
    ]
