# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app1', '0010_auto_20170322_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], max_length=1, null=True),
        ),
    ]
