# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-01 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_ownreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.IntegerField()),
                ('report_count', models.IntegerField()),
            ],
        ),
    ]
