# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-01 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_reportcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='report',
            field=models.IntegerField(default=0),
        ),
    ]
