# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_story_report'),
        ('app1', '0012_auto_20170802_0347'),
    ]

    operations = [
    ]
