# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 16:46
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app1', '0012_story_created_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Place',
        ),
        migrations.AddField(
            model_name='story',
            name='budget',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='type_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
