# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-02 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_merge_20170802_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Other')], max_length=1, null=True),
        ),
    ]
