# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_merge_20170802_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click_url_track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('page_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Place')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Other')], max_length=1, null=True),
        ),
    ]
