# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20170324_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_division',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.Division'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='app1.Division'),
        ),
    ]
