# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20170804_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='budget',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
