# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20170804_0102'),
        ('app1', '0016_auto_20170804_1554'),
    ]

    operations = [
    ]
